print('Multiple line Comment')
name=input('my name is: ')
age= input ('my age is: ')
country=input("I'm from: ")
print (type(name))
print (type(age))
print (type(country))
print('name: ' + name)
print('Age: ' + age)
print('country: ' + country)
msg= f'Hello,my name is {name} And I am {age} Years Old and I live in {country}'
print(msg)